const String init = 'Iniciado',
    bloqued = 'Bloqueado',
    pending = 'Pendiete',
    finish = 'Terminado',
    create = 'Crear',
    cancel = 'Cancelar',
    createTask = 'Crear tarea',
    putTaskName = 'Ingrese el nombre de la tarea',
    putDescription = 'Ingrese la descripcion';
